{% set name = "threddsclient" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6778e052e3a512caeca1d5f44f54b9b4b895f0301de9f62619cd866db365c60f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - beautifulsoup4
    - lxml

test:
  imports:
    - threddsclient
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/bird-house/threddsclient
  license: Apache-2.0
  license_file: LICENCE.txt
  summary: Thredds catalog client in Python
  doc_url: https://pypi.org/project/threddsclient/
  dev_url: https://github.com/bird-house/threddsclient

extra:
  recipe-maintainers:
    - fmigneault
    - Zeitsperre
    - cehbrecht
    - davidcaron
